[package]
name = "elementalist"
version = "0.1.0"
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies.built]
version = "0.7"
features = ["git2"]

[dependencies]
# When running the game in development, use the dynamic linking feature of Bevy to speed
# up compilation times. `cargo run --features bevy/dynamic_linking` will enable this.
bevy = "0.12.1"
bevy_pkv = "0.9.0"
leafwing-input-manager = "0.11.2"
serde = "1.0.194"
tracing = "0.1.40"
game_library = { path = "../game_library" }
