# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      minor-updates:
        update-types:
          - minor
          - patch
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
    groups:
      dev-dependencies:
        dependency-type: development
        update-types:
          - minor
          - major
          - patch
      prod-dependencies:
        dependency-type: production
        update-types:
          - minor
          - patch
  - package-ecosystem: pnpm
    directory: /
    schedule:
      interval: weekly
    groups:
      all:
        update-types:
          - patch
          - minor
          - major
